# ============================================
# БАЗА ДАННЫХ POSTGRESQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/forest_db?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
# ============================================
# HIBERNATE / JPA
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# ============================================
# ЗАГРУЗКА ФАЙЛОВ
# Максимальный размер запроса согласован с ForestStandController
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB
# ============================================
# ============================================
# НАСТРОЙКИ ПРИЛОЖЕНИЯ
# ============================================
# Игнорировать пересечения меньше 1 кв.м
forest.validation.min-area=1.0
forest.validation.tolerance=0.5
# ============================================
# THYMELEAF
# ============================================
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
# ============================================
# ЛОГИРОВАНИЕ
# ============================================
logging.level.com.alhrb.forestry=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.spatial=DEBUG
logging.level.org.springframework.transaction=DEBUG
# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin
# Для корректной работы с WebJars
spring.web.resources.add-mappings=true
spring.web.resources.static-locations=classpath:/META-INF/resources/webjars/,classpath:/static/,classpath:/public/

# Настройки хранения версий компонента, шаблонов отчетов
app.storage.report-templates-path=${user.home}/forestry/reports/templates
app.storage.report-out-path=${user.home}/forestry/reports
# Путь хранения документации
app.storage.docs-path=${user.home}/forestry/docs

# Настройки для хранения загруженных файлов
app.storage.file-upload-path=${user.home}/forestry/upload


spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
